name: CI
run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  pull_request:

env:
  GITHUB_ACTIONS: "true"

jobs:
  github-task-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show environment variable
        run: echo "ENV is $GITHUB_ACTIONS"
      
      - name: Show branch and repository name
        run: echo "Branch ${{ github.ref }}, Repository ${{ github.repository }}"
      
      - name: Show event name
        run: echo "Triggered by event ${{ github.event_name }}" 
